language: go
sudo: false

matrix:
  include:
    - go: "1.10"
    - go: "1.11"
    - go: "tip"

branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/
    
script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - /bin/bash ./scripts/ci_checks.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
      go: "1.11"

after_success:
  - mv ./cover/coverage.cov ./coverage.txt
  - bash <(curl -s https://codecov.io/bash)
  - rm -f ./coverage.txt
