// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anexia-it/geodbtools/mmdatformat (interfaces: Type)

// Package mmdatformat is a generated GoMock package.
package mmdatformat

import (
	geodbtools "github.com/anexia-it/geodbtools"
	gomock "github.com/golang/mock/gomock"
	io "io"
	reflect "reflect"
	time "time"
)

// MockType is a mock of Type interface
type MockType struct {
	ctrl     *gomock.Controller
	recorder *MockTypeMockRecorder
}

// MockTypeMockRecorder is the mock recorder for MockType
type MockTypeMockRecorder struct {
	mock *MockType
}

// NewMockType creates a new mock instance
func NewMockType(ctrl *gomock.Controller) *MockType {
	mock := &MockType{ctrl: ctrl}
	mock.recorder = &MockTypeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockType) EXPECT() *MockTypeMockRecorder {
	return m.recorder
}

// DatabaseType mocks base method
func (m *MockType) DatabaseType() geodbtools.DatabaseType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DatabaseType")
	ret0, _ := ret[0].(geodbtools.DatabaseType)
	return ret0
}

// DatabaseType indicates an expected call of DatabaseType
func (mr *MockTypeMockRecorder) DatabaseType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DatabaseType", reflect.TypeOf((*MockType)(nil).DatabaseType))
}

// EncodeTreeNode mocks base method
func (m *MockType) EncodeTreeNode(arg0 *uint32, arg1 *geodbtools.RecordTree) ([]byte, []*geodbtools.RecordTree, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncodeTreeNode", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]*geodbtools.RecordTree)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// EncodeTreeNode indicates an expected call of EncodeTreeNode
func (mr *MockTypeMockRecorder) EncodeTreeNode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncodeTreeNode", reflect.TypeOf((*MockType)(nil).EncodeTreeNode), arg0, arg1)
}

// NewReader mocks base method
func (m *MockType) NewReader(arg0 geodbtools.ReaderSource, arg1 DatabaseTypeID, arg2 string, arg3 *time.Time) (geodbtools.Reader, geodbtools.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewReader", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(geodbtools.Reader)
	ret1, _ := ret[1].(geodbtools.Metadata)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// NewReader indicates an expected call of NewReader
func (mr *MockTypeMockRecorder) NewReader(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewReader", reflect.TypeOf((*MockType)(nil).NewReader), arg0, arg1, arg2, arg3)
}

// NewWriter mocks base method
func (m *MockType) NewWriter(arg0 io.Writer, arg1 geodbtools.IPVersion) (geodbtools.Writer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewWriter", arg0, arg1)
	ret0, _ := ret[0].(geodbtools.Writer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewWriter indicates an expected call of NewWriter
func (mr *MockTypeMockRecorder) NewWriter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewWriter", reflect.TypeOf((*MockType)(nil).NewWriter), arg0, arg1)
}
